### ISSUE TITLE
Regular crashes

### ISSUE THREAD

**Issue by fuson** [indutny/node-spdy#173]
Looks like:

AssertionError: false == true
  at Stream.parseClientRequest [as _parseClientRequest] (/home/stss/node_modules/spdy/lib/spdy/stream.js:663:3)
  at Stream.write [as _write] (/home/stss/node_modules/spdy/lib/spdy/stream.js:880:10)
  at doWrite (_stream_writable.js:226:10)
  at writeOrBuffer (_stream_writable.js:216:5)
  at Stream.Writable.write (_stream_writable.js:183:11)
  at ClientRequest.OutgoingMessage._flush (http.js:1053:23)
  at http.js:1436:10
  at ClientRequest.onSocket (http.js:1775:17)
  at ClientRequest.g (events.js:180:16)
  at ClientRequest.EventEmitter.emit (events.js:117:20)
  at http.js:1758:9
  at process._tickCallback (node.js:415:13)

**Comment by indutny** [comment]
I have rewritten the library from scratch. Hopefully this is gone now.
