### ISSUE TITLE
  Error: New stream after GOAWAY

### ISSUE THREAD

**Issue by llambda** [indutny/node-spdy#213]
Getting the following with rc1. Chrome says "Failed to load resource: net::ERR_SPDY_COMPRESSION_ERROR"

```
  Error: New stream after GOAWAY
      at /home/u/app/node_modules/spdy/node_modules/spdy-transport/lib/spdy-transport/connection.js:615:26
      at Array.forEach (native)
      at Connection._goaway (/home/u/app/node_modules/spdy/node_modules/spdy-transport/lib/spdy-transport/connection.js:607:33)
      at Connection.handleGoaway [as _handleGoaway] (/home/u/app/node_modules/spdy/node_modules/spdy-transport/lib/spdy-transport/connection.js:512:8)
      at Connection._handleFrame (/home/u/app/node_modules/spdy/node_modules/spdy-transport/lib/spdy-transport/connection.js:304:10)
      at Parser.<anonymous> (/home/u/app/node_modules/spdy/node_modules/spdy-transport/lib/spdy-transport/connection.js:149:10)
      at emitOne (events.js:77:13)
      at Parser.emit (events.js:169:7)
      at readableAddChunk (/home/u/app/node_modules/spdy/node_modules/spdy-transport/node_modules/readable-stream/lib/_stream_readable.js:198:16)
      at Parser.Readable.push (/home/u/app/node_modules/spdy/node_modules/spdy-transport/node_modules/readable-stream/lib/_stream_readable.js:162:10)
      at Parser.Transform.push (/home/u/app/node_modules/spdy/node_modules/spdy-transport/node_modules/readable-stream/lib/_stream_transform.js:133:32)
      at next (/home/u/app/node_modules/spdy/node_modules/spdy-transport/lib/spdy-transport/protocol/base/parser.js:52:12)
      at /home/u/app/node_modules/spdy/node_modules/spdy-transport/lib/spdy-transport/protocol/http2/parser.js:70:5
      at Parser.onGoawayFrame (/home/u/app/node_modules/spdy/node_modules/spdy-transport/lib/spdy-transport/protocol/http2/parser.js:460:3)
      at Parser.onFrameBody (/home/u/app/node_modules/spdy/node_modules/spdy-transport/lib/spdy-transport/protocol/http2/parser.js:151:10)
      at Parser.execute (/home/u/app/node_modules/spdy/node_modules/spdy-transport/lib/spdy-transport/protocol/http2/parser.js:63:8)
      ```

**Comment by indutny** [comment]
@llambda interesting! Do you have a test case? I'm particularly interested in the headers that might be sent to the browser.

Did it crash?

**Comment by llambda** [comment]
Not sure if it crashed, was running under nodemon with autorestart. Unfortunately I haven't been able to reproduce the "New stream after GOAWAY", but I do get ERR_SPDY_COMPRESSION_ERROR consistently though.

**Comment by indutny** [comment]
@llambda do you think it might be possible to know the headers that were sent by your application? Or maybe a tcpdump either of client or server side?

**Comment by indutny** [comment]
Nah, ignore tcpdump this is TLS. It is all encrypted.

**Comment by llambda** [comment]
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwaG9uZW51bWJlciI6IjU1NTU1NTU1NTUiLCJpYXQiOjE0MzkyNjE4OTl9.WAPTyd0puz1g9hBEk4IOr_PY5g8Ze8ZXNQsAV4xiwCI
Referer: https://localhost:8443/?/conversations
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36
X-Requested-With: XMLHttpRequest

**Comment by llambda** [comment]
(Unfortunately, Chrome only gives "Provisional headers are shown", that's all the headers I could see on the failed request.)

**Comment by indutny** [comment]
@llambda I was actually talking about response headers that were sent by server.

**Comment by llambda** [comment]
Unfortunately Chrome doesn't show any, neither does firefox.

**Comment by indutny** [comment]
@llambda I'm going to add some debug logging to spdy. May I ask you to add an env variable and gist the logs after that?

**Comment by llambda** [comment]
Yes, sure. By the way, I discovered when I turn off 

app.use(require('koa-response-time')());

I no longer get ERR_SPDY_COMPRESSION_ERROR. However Authorization header seems to disappear from requests. I am trying to reproduce in a test case, but no luck yet.

**Comment by indutny** [comment]
Thank you so much!

Please give a try to spdy@2.0.0-rc2 and set `DEBUG="spdy:framer:extra"` in your environment variables before starting it.

**Comment by llambda** [comment]
https://gist.github.com/llambda/a8c06073ecf2d1624e16#file-gistfile1-txt-L23

**Comment by indutny** [comment]
@llambda looks like I still miss a few info :) May ask you to run it again with `DEBUG="spdy*"`?

**Comment by llambda** [comment]
Okay. I updated the gist above.

**Comment by llambda** [comment]
Here is another gist. This time reloading the site a few times as the debug output changes.

https://gist.github.com/llambda/dd0cccb3a78f045716a2

**Comment by indutny** [comment]
Thanks @llambda ! I'll figure it out (probably tomorrow)

**Comment by llambda** [comment]
Awesome :smile:

**Comment by indutny** [comment]
Fixed, it was really stupid: https://github.com/indutny/hpack.js/commit/101622f85193deb8c62a1982900465eec5376abc

**Comment by indutny** [comment]
Sorry!
