### ISSUE TITLE
Crashing the App with Safari Version 9.0 (11601.1.43)

### ISSUE THREAD

**Issue by debanjanbasu** [indutny/node-spdy#218]
TypeError: Cannot read property 'updateTableSize' of undefined
    at Connection._handleSettings (/Users/debanjanbasu/Desktop/inventman/node_modules/spdy/node_modules/spdy-transport/lib/spdy-transport/connection.js:459:21)
    at Connection._handleFrame (/Users/debanjanbasu/Desktop/inventman/node_modules/spdy/node_modules/spdy-transport/lib/spdy-transport/connection.js:298:10)
    at Parser.<anonymous> (/Users/debanjanbasu/Desktop/inventman/node_modules/spdy/node_modules/spdy-transport/lib/spdy-transport/connection.js:149:10)
    at Parser.emit (events.js:107:17)
    at readableAddChunk (/Users/debanjanbasu/Desktop/inventman/node_modules/spdy/node_modules/spdy-transport/node_modules/readable-stream/lib/_stream_readable.js:198:16)
    at Parser.Readable.push (/Users/debanjanbasu/Desktop/inventman/node_modules/spdy/node_modules/spdy-transport/node_modules/readable-stream/lib/_stream_readable.js:162:10)
    at Parser.Transform.push (/Users/debanjanbasu/Desktop/inventman/node_modules/spdy/node_modules/spdy-transport/node_modules/readable-stream/lib/_stream_transform.js:133:32)
    at next (/Users/debanjanbasu/Desktop/inventman/node_modules/spdy/node_modules/spdy-transport/lib/spdy-transport/protocol/base/parser.js:52:12)
    at /Users/debanjanbasu/Desktop/inventman/node_modules/spdy/node_modules/spdy-transport/lib/spdy-transport/protocol/http2/parser.js:71:5
    at Parser.onSettingsFrame (/Users/debanjanbasu/Desktop/inventman/node_modules/spdy/node_modules/spdy-transport/lib/spdy-transport/protocol/http2/parser.js:389:3)
    at Parser.onFrameBody (/Users/debanjanbasu/Desktop/inventman/node_modules/spdy/node_modules/spdy-transport/lib/spdy-transport/protocol/http2/parser.js:145:10)
    at Parser.execute (/Users/debanjanbasu/Desktop/inventman/node_modules/spdy/node_modules/spdy-transport/lib/spdy-transport/protocol/http2/parser.js:64:8)
    at Parser._consume (/Users/debanjanbasu/Desktop/inventman/node_modules/spdy/node_modules/spdy-transport/lib/spdy-transport/protocol/base/parser.js:92:8)
    at /Users/debanjanbasu/Desktop/inventman/node_modules/spdy/node_modules/spdy-transport/lib/spdy-transport/protocol/base/parser.js:60:12
    at process._tickCallback (node.js:355:11)

This is the error I'm getting with the latest version of Safari, which supports h2/spdy3.1. Nginx is working as expected, but node-spdy is breaking.

Testbed: OSX El Capitan
Node 0.12.7

**Comment by indutny** [comment]
Thank you, fixed in spdy-transport@1.1.7 - please run `npm update`.
