### ISSUE TITLE
Issue connecting to Apple's APNS servers

### ISSUE THREAD

**Issue by anandsuresh** [indutny/node-spdy#222]
Attempted to use node-spdy Agent with https to connect to the APNS servers, but ran into issues:

```
NODE_DEBUG="http" DEBUG="spdy*" node test/manual/apns.js asdf asdf
HTTP: write ret = false
HTTP: outgoing message end.
  spdy:client activating fallback +0ms
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at ClientRequest.addListener (events.js:160:15)
    at ClientRequest.once (events.js:185:8)
    at ClientRequest.abort (http.js:1460:10)
    at PoolEndpoint.check_timeouts (/Users/anandsuresh/voxer-inc/server/poolee/pool_endpoint.js:156:33)
    at null.<anonymous> (/Users/anandsuresh/voxer-inc/server/poolee/pool_endpoint.js:61:18)
    at wrapper [as _onTimeout] (timers.js:261:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

**Comment by anandsuresh** [comment]
Filed an issue as discussed. Let me know if you need any more information/logs.

**Comment by anandsuresh** [comment]
Fixed and working now.

**Comment by ethul** [comment]
Out of curiosity, what was the fix here? Thanks!

**Comment by indutny** [comment]
I don't remember :( Sorry!

**Comment by indutny** [comment]
Perhaps I just added ALPN support.

**Comment by ethul** [comment]
No problem. Thanks for the info.
