### ISSUE TITLE
Keep getting Error: request aborted

### ISSUE THREAD

**Issue by jackycute** [indutny/node-spdy#251]
Hi, I would like to use this repo to support http2 and spdy.
After I changed my server from `https` to `spdy`.
I got lots of below error during this time.

```
Error: request aborted
    at IncomingMessage.onAborted (/root/hackmd/node_modules/raw-body/index.js:269:10)
    at emitNone (events.js:80:13)
    at IncomingMessage.emit (events.js:179:7)
    at abortIncoming (_http_server.js:280:11)
    at Socket.serverSocketCloseListener (_http_server.js:293:5)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at net.js:475:12
    at /root/hackmd/node_modules/spdy-transport/lib/spdy-transport/stream.js:631:7
    at _combinedTickCallback (node.js:370:9)
    at process._tickDomainCallback (node.js:425:11)
```

server setup:

```
var options = {
        key: fs.readFileSync(config.sslkeypath, 'utf8'),
        cert: fs.readFileSync(config.sslcertpath, 'utf8'),
        ca: ca,
        dhparam: fs.readFileSync(config.dhparampath, 'utf8'),
        requestCert: false,
        rejectUnauthorized: false
    };
    var app = express();
    var server = require('spdy').createServer(options, app);
```

spdy v3.2.3
node v5.7.1

Also, this gain more memory consumption which reason might not clear yet.

Thanks for helping!

**Comment by jackycute** [comment]
OK, maybe it's my bad.
I revert it back to https but this error still there, I will re-open when needed.
Thanks anyway.
