### ISSUE TITLE
Error: Got RST: PROTOCOL_ERROR

### ISSUE THREAD

**Issue by NitroGhost** [indutny/node-spdy#266]
When ever I try to push an image or font, the first time loads fine, but on refresh get the following error:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Got RST: PROTOCOL_ERROR
    at Stream._handleRST (C:\Users\aileen\plug-pls\node_modules\spdy\node_modules\spdy-transport\lib\spdy-transport\stream.js:280:24)
    at Stream._handleFrame (C:\Users\aileen\plug-pls\node_modules\spdy\node_modules\spdy-transport\lib\spdy-transport\stream.js:126:10)
    at Connection._handleFrame (C:\Users\aileen\plug-pls\node_modules\spdy\node_modules\spdy-transport\lib\spdy-transport\connection.js:327:12)
    at Parser.<anonymous> (C:\Users\aileen\plug-pls\node_modules\spdy\node_modules\spdy-transport\lib\spdy-transport\connection.js:161:10)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at readableAddChunk (C:\Users\user\project\node_modules\spdy\node_modules\spdy-transport\node_modules\readable-stream\lib\_stream_readable.js:210:18)
    at Parser.Readable.push (C:\Users\user\project\node_modules\spdy\node_modules\spdy-transport\node_modules\readable-stream\lib\_stream_readable.js:169:10)
    at Parser.Transform.push (C:\Users\user\project\node_modules\spdy\node_modules\spdy-transport\node_modules\readable-stream\lib\_stream_transform.js:123:32)
    at next (C:\Users\user\project\node_modules\spdy\node_modules\spdy-transport\lib\spdy-transport\protocol\base\parser.js:52:12)
```
setup:
```
spdy.createServer(options, (req, res) => {
    if (req.url === "/") {
        if (req.isSpdy) {
            var stream = res.push("/fonts/some-font.woff", {
                method: "GET",
                request: {
                    accept: "*/*"
                },
                response: {
                    "content-type": "application/font-woff",
                    "content-encoding": "gzip"
                }
            });
            stream.on("err", function (err) {
                console.log(err);
            });
            fs.createReadStream("./public/fonts/some-font.woff")
            .pipe(zlib.createGzip())
            .pipe(stream);
        }
        res.end(htmlFile);
    }
}).listen(8080);
```

**Comment by indutny** [comment]
Hello! I'm afraid that the error name is `error`, not `err`. This is why your app is crashing. Sorry!

**Comment by NitroGhost** [comment]
I have changed it to error. is there a way to stop it from giving the Error: Got RST: PROTOCOL_ERROR ? I don't want it to fill the logs up every time a user requests the index.html

**Comment by wincinderith** [comment]
@indutny I can reproduce this issue.

**Comment by FlorianKoerner** [comment]
Agree with @wincinderith. Made the same observations.

**Comment by RezaErfani67** [comment]
not resolved for me...
![image](https://user-images.githubusercontent.com/24381986/110201222-31676600-7e77-11eb-93c9-622372f93337.png)
